#!/usr/bin/sh
#############################################################################################################################################################
###
### Version      : 1.0
### Script Usage : sh Folder_Structure.sh <Environment> 
### Description  : This Script will Create the Directory Structure Required.
###
#############################################################################################################################################################



if [ "$#" -ne 1 ]
then
	echo "The Script at least One Parameter to be passed"
	echo "Usage: sh Folder_Structure.sh <Environment>"
	exit 1
fi


GEN2ENV=$1


mkdir -p /home/dsadm/data/${GEN2ENV}/EAP
mkdir -p /home/dsadm/data/${GEN2ENV}/EAP/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/EAP/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/HIPPA_Notice
mkdir -p /home/dsadm/data/${GEN2ENV}/HIPPA_Notice/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/HIPPA_Notice/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/HIPPA_Notice/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/Email
mkdir -p /home/dsadm/data/${GEN2ENV}/IDCards
mkdir -p /home/dsadm/data/${GEN2ENV}/IDCards/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/IDCards/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/IDCards/BKP
mkdir -p /home/dsadm/data/${GEN2ENV}/IDCards/EmailAttch
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/PPO
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/PPO/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/PPO/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/PPO/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/PPO/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/PPO/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/PPO/Script
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/PPO/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/PPO/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/PPO/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/DHMO
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/DHMO/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/DHMO/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/DHMO/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/DHMO/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/DHMO/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/DHMO/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/DHMO/Email
mkdir -p /home/dsadm/data/${GEN2ENV}/CLEARING_HOUSE/DHMO/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/EPS
mkdir -p /home/dsadm/data/${GEN2ENV}/EPS/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/EPS/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/EPS/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/EPS/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/EPS/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/EPS/Processing
mkdir -p /home/dsadm/data/${GEN2ENV}/EPS/Reject
mkdir -p /home/dsadm/data/${GEN2ENV}/EPS/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/EPS/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/Scripts
mkdir -p /home/dsadm/data/${GEN2ENV}/Scripts/BKP
mkdir -p /home/dsadm/data/${GEN2ENV}/Scripts/Script_Logs
mkdir -p /home/dsadm/data/${GEN2ENV}/EHG
mkdir -p /home/dsadm/data/${GEN2ENV}/EHG/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/TESIA
mkdir -p /home/dsadm/data/${GEN2ENV}/TESIA/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/CPS
mkdir -p /home/dsadm/data/${GEN2ENV}/CPS/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/CPS/TESTA
mkdir -p /home/dsadm/data/${GEN2ENV}/CPS/TESTA/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/CPS/EHG
mkdir -p /home/dsadm/data/${GEN2ENV}/CPS/EHG/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/RDZ
mkdir -p /home/dsadm/data/${GEN2ENV}/RDZ/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/RDZ/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/RDZ/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/RDZ/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/RDZ/Audit
mkdir -p /home/dsadm/data/${GEN2ENV}/RDZ/Script
mkdir -p /home/dsadm/data/${GEN2ENV}/HYATT
mkdir -p /home/dsadm/data/${GEN2ENV}/HYATT/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/HYATT/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/HYATT/Email
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/PPO
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/PPO/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/PPO/Reject
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/PPO/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/PPO/Audit
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/PPO/Script
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/PPO/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/PPO/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/PPO/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/PPO/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/PPO/Email
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/PPO/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/DHMO
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/DHMO/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/DHMO/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/DHMO/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/DHMO/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/DHMO/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/DHMO/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/DHMO/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/CONDUENT/DHMO/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/RESERVES
mkdir -p /home/dsadm/data/${GEN2ENV}/RESERVES/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/RESERVES/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/RESERVES/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/RESERVES/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/RESERVES/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/SOH
mkdir -p /home/dsadm/data/${GEN2ENV}/SOH/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/SOH/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/SOH/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/LockBox
mkdir -p /home/dsadm/data/${GEN2ENV}/LockBox/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/LockBox/Reject
mkdir -p /home/dsadm/data/${GEN2ENV}/LockBox/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/LockBox/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/LockBox/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/LockBox/Processing
mkdir -p /home/dsadm/data/${GEN2ENV}/LockBox/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/GDI
mkdir -p /home/dsadm/data/${GEN2ENV}/GDI/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/GDI/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/GDI/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/GDI/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/GDI/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/TESTA
mkdir -p /home/dsadm/data/${GEN2ENV}/TESTA/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/GCAS
mkdir -p /home/dsadm/data/${GEN2ENV}/GCAS/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/GCAS/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/GCAS/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/GCAS/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/GCAS/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/GCAS/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/GCAS/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/GCAS/Common
mkdir -p /home/dsadm/data/${GEN2ENV}/Common
mkdir -p /home/dsadm/data/${GEN2ENV}/Metcheck
mkdir -p /home/dsadm/data/${GEN2ENV}/Metcheck/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/Metcheck/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/Metcheck/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/Metcheck/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/Metcheck/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/Metcheck/PasInputClaims
mkdir -p /home/dsadm/data/${GEN2ENV}/Metcheck/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/Metcheck/Script
mkdir -p /home/dsadm/data/${GEN2ENV}/Metcheck/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/Metcheck/PasInput
mkdir -p /home/dsadm/data/${GEN2ENV}/GEFT
mkdir -p /home/dsadm/data/${GEN2ENV}/GEFT/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/GEFT/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/GEFT/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/GEFT/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/GEFT/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/GEFT/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/GEFT/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/GEFT/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/GEFT/PasInput
mkdir -p /home/dsadm/data/${GEN2ENV}/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/NOVA
mkdir -p /home/dsadm/data/${GEN2ENV}/NOVA/DHMO
mkdir -p /home/dsadm/data/${GEN2ENV}/NOVA/DHMO/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/NOVA/DHMO/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/NOVA/DHMO/Email
mkdir -p /home/dsadm/data/${GEN2ENV}/NOVA/DHMO/Script
mkdir -p /home/dsadm/data/${GEN2ENV}/NOVA/DHMO/Reject
mkdir -p /home/dsadm/data/${GEN2ENV}/NOVA/DHMO/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/NOVA/DHMO/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/NOVA/DHMO/Audit
mkdir -p /home/dsadm/data/${GEN2ENV}/NOVA/DHMO/PasInput
mkdir -p /home/dsadm/data/${GEN2ENV}/NOVA/DHMO/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/NOVA/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/TCA
mkdir -p /home/dsadm/data/${GEN2ENV}/TCA/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/TCA/Reject
mkdir -p /home/dsadm/data/${GEN2ENV}/TCA/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/TCA/Audit
mkdir -p /home/dsadm/data/${GEN2ENV}/TCA/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/TCA/PasInput
mkdir -p /home/dsadm/data/${GEN2ENV}/TCA/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/TCA/Scripts
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRECON
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRECON/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRECON/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRECON/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRECON/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRECON/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRECON/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRECON/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRECON/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRECON/Script
mkdir -p /home/dsadm/data/${GEN2ENV}/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/HWSI
mkdir -p /home/dsadm/data/${GEN2ENV}/HWSI/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/HWSI/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/HWSI/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/HWSI/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/HWSI/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/HWSI/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/HWSI/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/HWSI/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/HWSI/Script
mkdir -p /home/dsadm/data/${GEN2ENV}/ERA
mkdir -p /home/dsadm/data/${GEN2ENV}/ERA/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/ERA/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/ERA/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/ERA/Archive/OUT
mkdir -p /home/dsadm/data/${GEN2ENV}/ERA/Archive/IN
mkdir -p /home/dsadm/data/${GEN2ENV}/ERA/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/ERA/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/ERA/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/ERA/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/ERA/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/ERA/Script
mkdir -p /home/dsadm/data/${GEN2ENV}/MUFS
mkdir -p /home/dsadm/data/${GEN2ENV}/MUFS/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/MUFS/Reject
mkdir -p /home/dsadm/data/${GEN2ENV}/MUFS/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/MUFS/Audit
mkdir -p /home/dsadm/data/${GEN2ENV}/MUFS/Script
mkdir -p /home/dsadm/data/${GEN2ENV}/MUFS/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/MUFS/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/MUFS/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/UCS_DENTAL
mkdir -p /home/dsadm/data/${GEN2ENV}/UCS_DENTAL/DENTAL_PROVIDER
mkdir -p /home/dsadm/data/${GEN2ENV}/UCS_DENTAL/DENTAL_PROVIDER/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/UCS_DENTAL/DENTAL_PROVIDER/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/UCS_DENTAL/DENTAL_PROVIDER/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/UCS_DENTAL/DENTAL_PROVIDER/Script
mkdir -p /home/dsadm/data/${GEN2ENV}/UCS_DENTAL/DENTAL_PROVIDER/Reject
mkdir -p /home/dsadm/data/${GEN2ENV}/UCS_DENTAL/DENTAL_PROVIDER/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/UCS_DENTAL/DENTAL_PROVIDER/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/UCS_DENTAL/DENTAL_PROVIDER/Audit
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPS
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPS/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPS/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPS/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPS/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPS/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPS/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPS/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPS/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPS/Script
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPS/Log
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRESP
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRESP/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRESP/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRESP/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRESP/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRESP/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRESP/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRESP/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRESP/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/EOPSRESP/Script
mkdir -p /home/dsadm/data/${GEN2ENV}/DBTOLoads
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Script
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Processing
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Processed
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Reject
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/ReProcessing
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Error
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Error_Processing
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Error_Processing/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Error_Processing/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Error_Processing/Processing
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Error_Processing/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Test
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Email
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Log
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Error1
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Remittance_Processing
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAREMITTANCE/Remittance_Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/TPE
mkdir -p /home/dsadm/data/${GEN2ENV}/TPE/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/CLASIC
mkdir -p /home/dsadm/data/${GEN2ENV}/CLASIC/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/CLASIC/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/CLASIC/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/CLASIC/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/CLASIC/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/CLASIC/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/CLASIC/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/CLASIC/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/CLASIC/Script
mkdir -p /home/dsadm/data/${GEN2ENV}/ICOMP
mkdir -p /home/dsadm/data/${GEN2ENV}/ICOMP/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/ICOMP/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/ICOMP/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/ICOMP/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/ICOMP/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/ICOMP/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/ICOMP/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/ICOMP/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/ICOMP/Scripts
mkdir -p /home/dsadm/data/${GEN2ENV}/MASTERTAX
mkdir -p /home/dsadm/data/${GEN2ENV}/MASTERTAX/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/MASTERTAX/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/MASTERTAX/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/MASTERTAX/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/MASTERTAX/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/MASTERTAX/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/MASTERTAX/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/MASTERTAX/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/MASTERTAX/Script
mkdir -p /home/dsadm/data/${GEN2ENV}/MASTERTAX/Email
mkdir -p /home/dsadm/data/${GEN2ENV}/MASTERTAX/Response
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Script
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/EDI
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/EDI/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/EDI/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/EDI/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/EDI/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/EDI/Processing
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Email
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Informatica_Grouping_Files
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Non_Informatica_Grouping_Files
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Non_Informatica_Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Non_Informatica_Processing
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/IIBError
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Informatica_Processing
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Informatica
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Intermediate_Grouping_Files
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Error
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Error_Processing
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Error_Processing/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Error_Processing/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Error_Processing/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Error_Processing/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Error_Processing/Sanity_Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/ReProcessing
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Processed
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/CoreInput
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Log
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Processing
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Intermediate_Grouping_Files_Bfr_Class
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Intermediate_Grouping_Files_Aftr_Class
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/JAVA_Processing
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/JAVA_Processing/PREV_DAY
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/JAVA_Processing/CURR_DAY
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/JAVA_Processing/PROCESSED
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/INITIAL
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/ONGOING
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Prev_File_Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Intermediate_Processing_Files
mkdir -p /home/dsadm/data/${GEN2ENV}/TPAENROLLMENT/Intermediate_Processing_Files/Majesco_Files
mkdir -p /home/dsadm/data/${GEN2ENV}/METFACS2
mkdir -p /home/dsadm/data/${GEN2ENV}/METFACS2/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/METFACS2/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/METFACS2/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/CDF
mkdir -p /home/dsadm/data/${GEN2ENV}/CDF/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/CDF/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/CDF/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/CDF/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/CDF/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/CDF/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/CDF/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/CDF/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/CDF/Script
mkdir -p /home/dsadm/data/${GEN2ENV}/EDM
mkdir -p /home/dsadm/data/${GEN2ENV}/EDM/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/EDM/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/EDM/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/EDM/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/TAXPORT
mkdir -p /home/dsadm/data/${GEN2ENV}/TAXPORT/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/TAXPORT/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/TAXPORT/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/TAXPORT/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/TAXPORT/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/TAXPORT/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/TAXPORT/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/TAXPORT/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/TAXPORT/Script
mkdir -p /home/dsadm/data/${GEN2ENV}/Conduent
mkdir -p /home/dsadm/data/${GEN2ENV}/Conduent/Output
mkdir -p /home/dsadm/data/${GEN2ENV}/Conduent/Input
mkdir -p /home/dsadm/data/${GEN2ENV}/Conduent/Archive
mkdir -p /home/dsadm/data/${GEN2ENV}/Conduent/Process
mkdir -p /home/dsadm/data/${GEN2ENV}/Conduent/Intermediate
mkdir -p /home/dsadm/data/${GEN2ENV}/Conduent/Dataset
mkdir -p /home/dsadm/data/${GEN2ENV}/Conduent/PasOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/Conduent/IIBOutput
mkdir -p /home/dsadm/data/${GEN2ENV}/Conduent/Script
mkdir -p /home/dsadm/data/${GEN2ENV}/Scripts
mkdir -p /home/dsadm/data/${GEN2ENV}/Scripts/Script_Logs
